import { describe, expect, it } from "vitest";

import { peertubeShortUUIDToUUID } from "@/lib/peertube-short-uuid";
import { uuidToShortId } from "@/lib/short-id";

// Generated by running the real `short-uuid` 6.0.3 with its default settings —
// the package and configuration PeerTube itself uses. Not hand-derived: the
// whole point is to be byte-compatible with an implementation we do not control.
const VECTORS: Array<[string, string]> = [
  ["eJaRdy8V19Uw6bHFwAaX5P", "6f2a1c3d-4b5e-4f60-8a71-9c0d2e3f4a5b"],
  ["2Vsa15MaKA7X3rP2CeH3H5", "0f8fad5b-d9cb-469f-a165-70867728950e"],
  ["111111114Ay6byqtQtQyDP", "00000000-0000-4000-8000-000000000001"],
  ["1111111111111111111111", "00000000-0000-0000-0000-000000000000"],
  ["xBuEXKpA6iqZQK5Kf2TnkV", "ffffffff-ffff-ffff-ffff-ffffffffffff"],
  ["8uCPfDJ7ApQgMVqaKzEyPW", "3caf7bea-5ceb-4959-81a0-b44d184e897c"],
];

describe("peertubeShortUUIDToUUID", () => {
  it("matches short-uuid's own output", () => {
    for (const [sid, uuid] of VECTORS) {
      expect(peertubeShortUUIDToUUID(sid)).toBe(uuid);
    }
  });

  it("requires exactly 22 characters, because short-uuid pads to a fixed width", () => {
    expect(peertubeShortUUIDToUUID("")).toBeNull();
    expect(peertubeShortUUIDToUUID("eJaRdy8V19Uw6bHFwAaX5")).toBeNull(); // 21
    expect(peertubeShortUUIDToUUID("eJaRdy8V19Uw6bHFwAaX5PP")).toBeNull(); // 23
  });

  it("rejects the characters base58 leaves out", () => {
    for (const bad of ["0", "O", "I", "l"]) {
      expect(peertubeShortUUIDToUUID("111111111111111111111" + bad)).toBeNull();
    }
  });

  // THE TRAP THIS MODULE EXISTS FOR, in its two forms.
  //
  // Both alphabets hold the same 58 characters, so a vidra sid is always a
  // well-formed PeerTube shortUUID and vice versa. Cross-decoding therefore
  // never fails on SHAPE. What happens instead depends on the value:
  //
  //   - often the number lands above 2^128 (flickr sorts uppercase last, so a
  //     leading capital is a huge digit) and the 16-byte guard rejects it;
  //   - but sometimes it lands in range and produces a perfectly well-formed
  //     uuid naming a DIFFERENT video. That is the dangerous case, and no
  //     shape check can catch it — only never mixing the tables.
  it("rejects a vidra sid whose value overflows 16 bytes", () => {
    const vidraSid = uuidToShortId("6f2a1c3d-4b5e-4f60-8a71-9c0d2e3f4a5b")!;
    expect(vidraSid).toBe("EjArDZ8v19uX6BigXbAx5p");
    expect(vidraSid).toHaveLength(22); // same length as a PeerTube shortUUID
    expect(peertubeShortUUIDToUUID(vidraSid)).toBeNull();
  });

  it("silently yields a WRONG video for a vidra sid that happens to be in range", () => {
    // Found by search over random uuids. The misdecode is well-formed and would
    // resolve against a real lookup, which is exactly why the two decoders must
    // never be pointed at the same route.
    const uuid = "1c2238ef-d8e7-4249-8ed9-f3293e325a37";
    const vidraSid = uuidToShortId(uuid)!;
    expect(vidraSid).toBe("4UVm9F6k8z6EDn7yc4QxHt");

    const misdecoded = peertubeShortUUIDToUUID(vidraSid);
    expect(misdecoded).toBe("1faef7f1-63d5-b3f3-7299-d8d756bc4b51");
    expect(misdecoded).not.toBe(uuid); // a different video entirely
  });

  it("is the exact inverse of the vectors' encoding, not an approximation", () => {
    for (const [sid, uuid] of VECTORS) {
      const decoded = peertubeShortUUIDToUUID(sid)!;
      expect(decoded).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
      expect(decoded).toBe(uuid);
    }
  });
});
